[tool.aerich]
tortoise_orm = "main.TORTOISE_ORM"
location = "./migrations"
src_folder = "./."

# Tortoise-ORM - это библиотека для асинхронной работы с базами данных в Python,
#разработанная специально для использования с асинхронными фреймворками,
#такими как asyncio. Она предоставляет удобный способ взаимодействия с базами данных,
#абстрагируясь от деталей SQL-запросов и позволяя вам работать с объектами Python.
#
#
# С помощью Tortoise-ORM вы можете определять модели баз данных с использованием классов Python,
#и Tortoise обрабатывает трансляцию этих моделей в SQL-запросы. Он поддерживает различные бэкэнды баз данных,
#такие как SQLite, PostgreSQL и MySQL.
#
#
# Его асинхронная природа делает его отличным выбором для высокопроизводительных,
#веб-приложений и других асинхронных проектов на Python.